# ── SEED DATA MODULE ─────────────────────────────────────────────────────────
# Called by POST /api/v1/admin/seed
# 10 Poli, 30 Dokter (L+P), 20 Admin Users, rich schedules, visit histories

POLIS = [
    {"name": "Poli Umum",          "room": "Ruang 101", "floor": "Lantai 1", "description": "Pelayanan kesehatan umum dan pemeriksaan dasar"},
    {"name": "Poli Anak",           "room": "Ruang 102", "floor": "Lantai 1", "description": "Pelayanan kesehatan bayi, anak, dan remaja"},
    {"name": "Poli Jantung",        "room": "Ruang 201", "floor": "Lantai 2", "description": "Pemeriksaan dan penanganan penyakit kardiovaskular"},
    {"name": "Poli Mata",           "room": "Ruang 202", "floor": "Lantai 2", "description": "Pemeriksaan dan penanganan gangguan penglihatan"},
    {"name": "Poli Gigi",           "room": "Ruang 203", "floor": "Lantai 2", "description": "Perawatan gigi, mulut, dan rahang"},
    {"name": "Poli Kulit",          "room": "Ruang 301", "floor": "Lantai 3", "description": "Penanganan penyakit kulit, kelamin, dan estetika"},
    {"name": "Poli Saraf",          "room": "Ruang 302", "floor": "Lantai 3", "description": "Pemeriksaan dan penanganan gangguan sistem saraf"},
    {"name": "Poli Ortopedi",       "room": "Ruang 303", "floor": "Lantai 3", "description": "Penanganan tulang, sendi, dan otot"},
    {"name": "Poli Kandungan",      "room": "Ruang 401", "floor": "Lantai 4", "description": "Pelayanan kesehatan reproduksi wanita dan kebidanan"},
    {"name": "Poli Farmasi",        "room": "Ruang 105", "floor": "Lantai 1", "description": "Pengambilan dan konsultasi obat"},
]

DOCTORS = [
    # Poli Umum (3 dokter)
    {"name": "dr. Ahmad Fauzi, Sp.PD",       "spec": "Penyakit Dalam",       "poli": "Poli Umum",     "gender": "L",
     "bio": "Dokter spesialis penyakit dalam dengan pengalaman 15 tahun. Berfokus pada penanganan diabetes, hipertensi, dan penyakit metabolik.",
     "edu": "FK Universitas Indonesia, Sp.PD RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Siti Rahayu, Sp.PD",       "spec": "Penyakit Dalam",       "poli": "Poli Umum",     "gender": "P",
     "bio": "Spesialis penyakit dalam yang berpengalaman dalam penanganan penyakit autoimun dan reumatologi.",
     "edu": "FK Universitas Gadjah Mada, Sp.PD RSUP Dr. Sardjito",
     "days": "Selasa, Kamis, Sabtu"},
    {"name": "dr. Budi Hartono",              "spec": "Dokter Umum",          "poli": "Poli Umum",     "gender": "L",
     "bio": "Dokter umum dengan keahlian dalam penanganan penyakit infeksi dan pemeriksaan kesehatan rutin.",
     "edu": "FK Universitas Airlangga Surabaya",
     "days": "Senin, Selasa, Rabu, Kamis, Jumat"},
    # Poli Anak (3 dokter)
    {"name": "dr. Dewi Kusuma, Sp.A",         "spec": "Spesialis Anak",       "poli": "Poli Anak",     "gender": "P",
     "bio": "Dokter spesialis anak dengan keahlian khusus dalam tumbuh kembang anak dan imunisasi.",
     "edu": "FK Universitas Padjadjaran, Sp.A RSHS Bandung",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Rizky Pratama, Sp.A",       "spec": "Spesialis Anak",       "poli": "Poli Anak",     "gender": "L",
     "bio": "Spesialis anak yang berfokus pada penanganan alergi dan imunologi anak.",
     "edu": "FK Universitas Diponegoro, Sp.A RSUP Dr. Kariadi",
     "days": "Selasa, Kamis"},
    {"name": "dr. Nurul Hidayah, Sp.A",       "spec": "Spesialis Anak",       "poli": "Poli Anak",     "gender": "P",
     "bio": "Dokter anak dengan pengalaman 10 tahun dalam penanganan penyakit infeksi anak dan neonatologi.",
     "edu": "FK Universitas Brawijaya, Sp.A RSUD Dr. Saiful Anwar",
     "days": "Senin, Selasa, Kamis, Sabtu"},
    # Poli Jantung (3 dokter)
    {"name": "dr. Hendra Wijaya, Sp.JP",      "spec": "Spesialis Jantung",    "poli": "Poli Jantung",  "gender": "L",
     "bio": "Kardiolog berpengalaman dalam penanganan gagal jantung, aritmia, dan intervensi koroner.",
     "edu": "FK Universitas Indonesia, Sp.JP RSCM Jakarta, Fellowship Kardiologi Intervensi",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Lestari Wulandari, Sp.JP",  "spec": "Spesialis Jantung",    "poli": "Poli Jantung",  "gender": "P",
     "bio": "Spesialis jantung dengan keahlian ekokardiografi dan penanganan penyakit jantung bawaan.",
     "edu": "FK Universitas Gadjah Mada, Sp.JP RSUP Dr. Sardjito",
     "days": "Selasa, Kamis"},
    {"name": "dr. Agus Setiawan, Sp.JP",      "spec": "Spesialis Jantung",    "poli": "Poli Jantung",  "gender": "L",
     "bio": "Kardiolog dengan spesialisasi rehabilitasi jantung dan pencegahan penyakit kardiovaskular.",
     "edu": "FK Universitas Airlangga, Sp.JP RSUD Dr. Soetomo",
     "days": "Rabu, Jumat, Sabtu"},
    # Poli Mata (3 dokter)
    {"name": "dr. Indah Permata, Sp.M",       "spec": "Spesialis Mata",       "poli": "Poli Mata",     "gender": "P",
     "bio": "Dokter mata dengan keahlian bedah katarak, glaukoma, dan retina.",
     "edu": "FK Universitas Indonesia, Sp.M RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Fajar Nugroho, Sp.M",       "spec": "Spesialis Mata",       "poli": "Poli Mata",     "gender": "L",
     "bio": "Spesialis mata yang berfokus pada penanganan kelainan refraksi dan bedah LASIK.",
     "edu": "FK Universitas Padjadjaran, Sp.M RSHS Bandung",
     "days": "Selasa, Kamis, Sabtu"},
    {"name": "dr. Ratna Sari, Sp.M",          "spec": "Spesialis Mata",       "poli": "Poli Mata",     "gender": "P",
     "bio": "Dokter mata dengan pengalaman dalam penanganan penyakit mata anak dan strabismus.",
     "edu": "FK Universitas Diponegoro, Sp.M RSUP Dr. Kariadi",
     "days": "Senin, Selasa, Kamis"},
    # Poli Gigi (3 dokter)
    {"name": "drg. Andi Saputra, Sp.KG",      "spec": "Spesialis Konservasi Gigi", "poli": "Poli Gigi", "gender": "L",
     "bio": "Dokter gigi spesialis konservasi dengan keahlian perawatan saluran akar dan restorasi estetik.",
     "edu": "FKG Universitas Indonesia, Sp.KG RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "drg. Maya Putri, Sp.Ort",       "spec": "Spesialis Ortodonti",  "poli": "Poli Gigi",     "gender": "P",
     "bio": "Spesialis ortodonti dengan pengalaman pemasangan behel konvensional dan clear aligner.",
     "edu": "FKG Universitas Gadjah Mada, Sp.Ort RSUP Dr. Sardjito",
     "days": "Selasa, Kamis, Sabtu"},
    {"name": "drg. Rudi Santoso",             "spec": "Dokter Gigi Umum",     "poli": "Poli Gigi",     "gender": "L",
     "bio": "Dokter gigi umum dengan keahlian pencabutan, penambalan, dan pembersihan karang gigi.",
     "edu": "FKG Universitas Airlangga Surabaya",
     "days": "Senin, Selasa, Rabu, Kamis, Jumat"},
    # Poli Kulit (3 dokter)
    {"name": "dr. Cantika Dewi, Sp.KK",       "spec": "Spesialis Kulit & Kelamin", "poli": "Poli Kulit", "gender": "P",
     "bio": "Dermatolog dengan keahlian penanganan akne, psoriasis, dan prosedur estetika kulit.",
     "edu": "FK Universitas Indonesia, Sp.KK RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Bagas Wicaksono, Sp.KK",    "spec": "Spesialis Kulit & Kelamin", "poli": "Poli Kulit", "gender": "L",
     "bio": "Spesialis kulit dengan fokus pada dermatologi anak dan penanganan penyakit infeksi kulit.",
     "edu": "FK Universitas Padjadjaran, Sp.KK RSHS Bandung",
     "days": "Selasa, Kamis"},
    {"name": "dr. Fitri Handayani, Sp.KK",    "spec": "Spesialis Kulit & Kelamin", "poli": "Poli Kulit", "gender": "P",
     "bio": "Dermatolog estetika dengan pengalaman laser, chemical peeling, dan filler.",
     "edu": "FK Universitas Diponegoro, Sp.KK RSUP Dr. Kariadi",
     "days": "Rabu, Jumat, Sabtu"},
    # Poli Saraf (3 dokter)
    {"name": "dr. Wahyu Hidayat, Sp.S",       "spec": "Spesialis Saraf",      "poli": "Poli Saraf",    "gender": "L",
     "bio": "Neurolog dengan keahlian penanganan stroke, epilepsi, dan penyakit Parkinson.",
     "edu": "FK Universitas Indonesia, Sp.S RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Anisa Maharani, Sp.S",      "spec": "Spesialis Saraf",      "poli": "Poli Saraf",    "gender": "P",
     "bio": "Spesialis saraf yang berfokus pada penanganan nyeri kepala, migrain, dan gangguan tidur.",
     "edu": "FK Universitas Gadjah Mada, Sp.S RSUP Dr. Sardjito",
     "days": "Selasa, Kamis, Sabtu"},
    {"name": "dr. Doni Kurniawan, Sp.S",      "spec": "Spesialis Saraf",      "poli": "Poli Saraf",    "gender": "L",
     "bio": "Neurolog dengan spesialisasi neurointervensi dan penanganan cedera otak.",
     "edu": "FK Universitas Airlangga, Sp.S RSUD Dr. Soetomo",
     "days": "Senin, Selasa, Kamis"},
    # Poli Ortopedi (3 dokter)
    {"name": "dr. Surya Pratama, Sp.OT",      "spec": "Spesialis Ortopedi",   "poli": "Poli Ortopedi", "gender": "L",
     "bio": "Ortopedi dengan keahlian bedah lutut, penggantian sendi, dan penanganan fraktur.",
     "edu": "FK Universitas Indonesia, Sp.OT RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Yuni Astuti, Sp.OT",        "spec": "Spesialis Ortopedi",   "poli": "Poli Ortopedi", "gender": "P",
     "bio": "Spesialis ortopedi dengan fokus pada penanganan skoliosis dan kelainan tulang belakang.",
     "edu": "FK Universitas Padjadjaran, Sp.OT RSHS Bandung",
     "days": "Selasa, Kamis"},
    {"name": "dr. Eko Prasetyo, Sp.OT",       "spec": "Spesialis Ortopedi",   "poli": "Poli Ortopedi", "gender": "L",
     "bio": "Ortopedi olahraga dengan pengalaman penanganan cedera ligamen dan rehabilitasi atlet.",
     "edu": "FK Universitas Diponegoro, Sp.OT RSUP Dr. Kariadi",
     "days": "Rabu, Jumat, Sabtu"},
    # Poli Kandungan (3 dokter)
    {"name": "dr. Melati Suci, Sp.OG",        "spec": "Spesialis Kandungan",  "poli": "Poli Kandungan","gender": "P",
     "bio": "Dokter kandungan dengan keahlian USG 4D, penanganan kehamilan risiko tinggi, dan laparoskopi.",
     "edu": "FK Universitas Indonesia, Sp.OG RSCM Jakarta",
     "days": "Senin, Rabu, Jumat"},
    {"name": "dr. Putri Anggraini, Sp.OG",    "spec": "Spesialis Kandungan",  "poli": "Poli Kandungan","gender": "P",
     "bio": "Spesialis kandungan yang berfokus pada onkologi ginekologi dan penanganan kanker serviks.",
     "edu": "FK Universitas Gadjah Mada, Sp.OG RSUP Dr. Sardjito",
     "days": "Selasa, Kamis, Sabtu"},
    {"name": "dr. Bambang Susilo, Sp.OG",     "spec": "Spesialis Kandungan",  "poli": "Poli Kandungan","gender": "L",
     "bio": "Dokter kandungan dengan pengalaman 20 tahun dalam persalinan normal dan operasi caesar.",
     "edu": "FK Universitas Airlangga, Sp.OG RSUD Dr. Soetomo",
     "days": "Senin, Selasa, Rabu, Kamis"},
    # Poli Farmasi (2 dokter/apoteker)
    {"name": "apt. Rini Wulandari, S.Farm",   "spec": "Apoteker Klinis",      "poli": "Poli Farmasi",  "gender": "P",
     "bio": "Apoteker klinis dengan keahlian konsultasi obat, interaksi obat, dan farmasi onkologi.",
     "edu": "Farmasi Universitas Indonesia, Apoteker RSCM Jakarta",
     "days": "Senin, Selasa, Rabu, Kamis, Jumat"},
    {"name": "apt. Dimas Aditya, S.Farm",     "spec": "Apoteker Klinis",      "poli": "Poli Farmasi",  "gender": "L",
     "bio": "Apoteker dengan spesialisasi farmasi geriatri dan manajemen terapi obat kronis.",
     "edu": "Farmasi Universitas Gadjah Mada, Apoteker RSUP Dr. Sardjito",
     "days": "Senin, Rabu, Jumat, Sabtu"},
    # Tambahan dokter umum untuk genap 30
    {"name": "dr. Laila Fitriani",            "spec": "Dokter Umum",          "poli": "Poli Umum",     "gender": "P",
     "bio": "Dokter umum dengan keahlian dalam penanganan penyakit kronis dan konsultasi gizi.",
     "edu": "FK Universitas Brawijaya Malang",
     "days": "Senin, Selasa, Rabu, Kamis, Jumat"},
    {"name": "dr. Teguh Santoso",             "spec": "Dokter Umum",          "poli": "Poli Umum",     "gender": "L",
     "bio": "Dokter umum dengan pengalaman di IGD dan penanganan kegawatdaruratan medis.",
     "edu": "FK Universitas Hasanuddin Makassar",
     "days": "Selasa, Kamis, Sabtu"},
]

STAFF = [
    # Administrator
    {"username": "administrator",  "password": "admin123",    "role": "administrator", "name": "Admin Utama"},
    # Petugas Panggil (5 orang)
    {"username": "petugas",        "password": "panggil123",  "role": "petugas",       "name": "Petugas Antrian 1"},
    {"username": "petugas2",       "password": "panggil456",  "role": "petugas",       "name": "Petugas Antrian 2"},
    {"username": "petugas3",       "password": "panggil789",  "role": "petugas",       "name": "Petugas Antrian 3"},
    {"username": "petugas_pagi",   "password": "pagi1234",    "role": "petugas",       "name": "Petugas Shift Pagi"},
    {"username": "petugas_siang",  "password": "siang1234",   "role": "petugas",       "name": "Petugas Shift Siang"},
    # Console / Loket (6 orang)
    {"username": "console",        "password": "console123",  "role": "console",       "name": "Loket 1 - Pendaftaran"},
    {"username": "loket2",         "password": "loket2024",   "role": "console",       "name": "Loket 2 - Pendaftaran"},
    {"username": "loket3",         "password": "loket3024",   "role": "console",       "name": "Loket 3 - Pendaftaran"},
    {"username": "loket_anak",     "password": "anakloket1",  "role": "console",       "name": "Loket Khusus Anak"},
    {"username": "loket_bpjs",     "password": "bpjs2024",    "role": "console",       "name": "Loket BPJS"},
    {"username": "loket_umum",     "password": "umum2024",    "role": "console",       "name": "Loket Pasien Umum"},
    # Display (4 layar)
    {"username": "display",        "password": "display123",  "role": "display",       "name": "Display Lantai 1"},
    {"username": "display2",       "password": "display456",  "role": "display",       "name": "Display Lantai 2"},
    {"username": "display3",       "password": "display789",  "role": "display",       "name": "Display Lantai 3"},
    {"username": "display4",       "password": "display000",  "role": "display",       "name": "Display Lantai 4"},
    # Admin tambahan
    {"username": "admin_it",       "password": "it2024rs",    "role": "administrator", "name": "Admin IT"},
    {"username": "admin_rekam",    "password": "rekam2024",   "role": "administrator", "name": "Admin Rekam Medis"},
    {"username": "admin_keuangan", "password": "keuangan24",  "role": "administrator", "name": "Admin Keuangan"},
    {"username": "supervisor",     "password": "super2024",   "role": "administrator", "name": "Supervisor Pelayanan"},
]

VISIT_DIAGNOSES = [
    ("Hipertensi grade 1, terapi antihipertensi dilanjutkan", "Poli Umum"),
    ("Diabetes mellitus tipe 2 terkontrol, HbA1c 7.2%", "Poli Umum"),
    ("ISPA ringan, diberikan antibiotik dan antipiretik", "Poli Umum"),
    ("Tumbuh kembang normal, imunisasi DPT booster", "Poli Anak"),
    ("Bronkitis akut pada anak, nebulisasi dan antibiotik", "Poli Anak"),
    ("Diare akut dehidrasi ringan, rehidrasi oral", "Poli Anak"),
    ("Aritmia supraventrikular, EKG normal sinus rhythm", "Poli Jantung"),
    ("Hipertensi dengan LVH, terapi ACE inhibitor", "Poli Jantung"),
    ("Katarak senilis OD, rencana operasi fakoemulsifikasi", "Poli Mata"),
    ("Miopia tinggi, diresepkan kacamata -5.00 D", "Poli Mata"),
    ("Karies gigi 36, dilakukan penambalan komposit", "Poli Gigi"),
    ("Periodontitis kronis, scaling dan root planing", "Poli Gigi"),
    ("Dermatitis atopik, terapi kortikosteroid topikal", "Poli Kulit"),
    ("Akne vulgaris grade 3, isotretinoin oral", "Poli Kulit"),
    ("Migrain kronik, terapi preventif topiramat", "Poli Saraf"),
    ("Carpal tunnel syndrome bilateral, fisioterapi", "Poli Saraf"),
    ("Osteoartritis lutut bilateral, injeksi kortikosteroid", "Poli Ortopedi"),
    ("Fraktur radius distal, pemasangan gips sirkuler", "Poli Ortopedi"),
    ("Kehamilan 32 minggu normal, USG biometri baik", "Poli Kandungan"),
    ("Mioma uteri, observasi dan terapi hormonal", "Poli Kandungan"),
]
